

class DailyInfoData{
  final String entry;
  final String exitdate;
  final String receipt;
  final String emm11no;
  final String vehicle;
  final String vehicletype;
  final String drivername;
  final String contactno;
  final String destination;
  final String quantity;

  DailyInfoData({
    required this.entry, 
    required this.exitdate, 
    required this.receipt, 
    required this.emm11no, 
    required this.vehicle, 
    required this.vehicletype, 
    required this.drivername, 
    required this.contactno, 
    required this.destination, 
    required this.quantity
});
factory DailyInfoData.fromJson(Map<String, dynamic>json)=> DailyInfoData(
  entry: json['entry'], 
  exitdate: json['exitdate'],
  receipt: json['receipt'], 
  emm11no: json['emm11no'], 
  vehicle: json['vehicle'], 
  vehicletype: json['vehicletype'], 
  drivername: json['drivername'],
  contactno: json['contactno'], 
  destination: json['destination'], 
  quantity: json['quantity'],
  );
}

List<DailyInfoData> dailyinfodata = [
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
   DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
  DailyInfoData(
    entry: "", 
    exitdate: "NO", 
    receipt: "RECORD", 
    emm11no: "FOUND", 
    vehicle: "", 
    vehicletype: "", 
    drivername: "", 
    contactno: "", 
    destination: "", 
    quantity: "",
  ),
];
